#!/bin/bash

export MAKEOPTS="-j16"
export EMERGE_DEFAULT_OPTS="--verbose --verbose-conflicts --autounmask y --autounmask-write y --binpkg-respect-use y --jobs=12 "
export PORTAGE_CHECKSUM_FILTER="-* sha512"
export PORTAGE_COMPRESS="bzip2"
export PORTAGE_COMPRESS_FLAGS="-1"
export CFLAGS="-O2 -pipe -march=core2 -mtune=core2"
export CXXFLAGS="${CFLAGS} "
export CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 ssse3"
export PROFILE_IS_HARDENED=1
export ACCEPT_KEYWORDS="~amd64"
export USE="-awt -bindist -branding -debug -consolekit -dbus -kdbus -policykit -pam -systemd -pulseaudio -udisks -upower -upnp -upnp-av -avahi -gvfs -gtk3 -qt4 -qt5 -gnome-keyring -libnotify -gnome -kde -ruby -test hardened urandom ipv6 sasl ssl openssl libressl curl_ssl_libressl -gnutls -nettle socks5 system-mitkrb5 usb threads nptl nls unicode bzip2 lzo lzma xz readline xml"
