#!/bin/bash

export MAKEOPTS="-j16"
export EMERGE_DEFAULT_OPTS="--autounmask y --autounmask-write y --jobs=8 "
export PORTAGE_CHECKSUM_FILTER="-* sha512"
export PORTAGE_COMPRESS=""
export PROFILE_IS_HARDENED=1
export ACCEPT_KEYWORDS="~amd64"
export USE="${USE} hardened urandom ipv6 livecd loop-aes -kdbus -bindist -branding -consolekit -policykit -pam -dbus -gvfs -gtk3 -gnome-keyring -systemd -pulseaudio static-libs"
