#!/bin/bash

# EVALUATION ORDER
# catalystrc sets ENVIRONMENT as may any other script do
# if no VAR is set in ENVIRONMENT make.conf sets variable
# catalyst-spec is additive to already set USE flags
# ENVIRONMENT supersedes package.use specific flags set

#export MAKEOPTS="-j 8"
export EMERGE_DEFAULT_OPTS="--verbose --verbose-conflicts --with-bdeps y --deep --complete-graph y --binpkg-respect-use y --load-average 8.0 -j"
export PORTAGE_CHECKSUM_FILTER="-* sha512"
export PORTAGE_COMPRESS="bzip2"
export PORTAGE_COMPRESS_FLAGS="-1"
#fomit-frame-pointer when debugging is not required
export CFLAGS="-O2 -pipe -fomit-frame-pointer -Wno-error"
export CXXFLAGS="${CFLAGS}"
export CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 ssse3"
export PROFILE_IS_HARDENED=1
export ACCEPT_KEYWORDS="~amd64"
export USE="-bindist -branding -debug -test -pam -systemd -consolekit -policykit -dbus -kdbus -oss -pulseaudio hardened urandom ipv6 sasl ssl libressl curl_ssl_libressl -gnutls -nettle threads nptl nls unicode bzip2 lzo lzma xz zlib readline fortran clang gmp openmp ghc smp static-libs"
#export GK_SHARE="/etc/portage/genkernel"
export PYTHON_SINGLE_TARGET="python2_7"
#export PYTHON_SINGLE_TARGET="python3_5"
export PYTHON_TARGETS="python2_7 python3_5 python3_6"
export ACCEPT_KEYWORDS="~amd64"

export SWITCH_CTARGET=x86_64-pc-linux-gnu-5.4.0

#export PORTAGE_TMPDIR=/var/tmp
export PORTAGE_NICENESS=8

export SHELL="/bin/bash"

export COLLISION_IGNORE="/usr/share/vim/*"
