#!/bin/bash

# overrides package.env specific noparallel if set here
#export MAKEOPTS="-j8 -l8"

export CHOST="x86_64-unknown-linux-uclibc"
export CHOST_amd64="x86_64-unknown-linux-uclibc"
#export CHOST_amd64="x86_64-gentoo-linux-uclibc"
#export CTARGET="x86_64-unknown-linux-uclibc" breaks
#export SWITCH_CTARGET=x86_64-pc-linux-gnu-8.2.0
export SWITCH_CTARGET=x86_64-unknown-linux-uclibc-8.2.0

export ACCEPT_KEYWORDS="~amd64"
export ACCEPT_LICENSE="-* @FREE"
export PROFILE_IS_HARDENED=1
export PAX_MARKINGS="PT"

export CFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"
export CXXFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"
export COMMON_FLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"
export BOOT_CFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"
export STAGE1_CFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"

export EMERGE_DEFAULT_OPTS="--verbose y --verbose-conflicts --verbose-slot-rebuilds y --binpkg-respect-use y --deep --complete-graph y --load-average 8.0 --jobs=64 --accept-properties=-interactive"

#export DISTDIR="/usr/distfiles" conflicts
#export PKGDIR="/var/tmp/packages" conflicts
#export PORTDIR_OVERLAY="/usr/local/portage"
export PORTDIR="/usr/portage"
export PORTAGE_TMPDIR=/var/tmp
export PORTAGE_NICENESS=18
export PORTAGE_REPO_DUPLICATE_WARN="0"
#export PORT_LOGDIR=/var/log/portage/

#export ELIBC=uclibc
export USE="-bindist -branding -debug -test -pam -systemd -consolekit -policykit -dbus -kdbus -oss -pulseaudio -udev acl caps hardened pax-kernel pie pic ssp uclibc urandom ipv6 sasl ssl libressl -gnutls -nettle threads nptl -idn -iconv -nls unicode bzip2 lzo lzma xz zlib readline fortran gmp openmp ghc smp -introspection"
# these break stage1 build already
#export BOOTSTRAP_USE=
#static-libs
#priority decreases from left to right
export USE_ORDER="pkg:env:conf:defaults:pkginternal:repo:env.d"

export CONFIG_PROTECT="-*"
#FEATURES="userfetch userpriv candy"
#FEATURES="splitdebug"
#INSTALL_MASK="/usr/lib/debug"
#PYTHON_SINGLE_TARGET="python2_7"
#PYTHON_TARGETS="python2_7 python3_5 python3_6"
export SHELL="/bin/bash"
export COLLISION_IGNORE="/usr/share/vim/* /usr/bin/smfsh /usr/bin/iconv /usr/include/iconv.h"

export PORTAGE_CHECKSUM_FILTER="-* sha256"
export PORTAGE_COMPRESS="gzip"
export PORTAGE_COMPRESS_FLAGS="-1"
export BINPKG_COMPRESS="lzop"
export BINPKG_COMPRESS_FLAGS="-1"
