#!/bin/bash
export ACCEPT_KEYWORDS="~amd64"
export ACCEPT_LICENSE="-* @FREE"
export PROFILE_IS_HARDENED=1

export EMERGE_DEFAULT_OPTS="--verbose y --verbose-conflicts --verbose-slot-rebuilds y --binpkg-respect-use y --deep --complete-graph y --load-average 8.0 --jobs=128 --accept-properties=-interactive"
export SWITCH_CTARGET=x86_64-pc-linux-gnu-8.2.0

#export DISTDIR="/usr/distfiles"
export PKGDIR="/var/tmp/packages"
#export PORTDIR_OVERLAY="/usr/local/portage"
export PORTDIR="/usr/portage"
export PORTAGE_TMPDIR=/var/tmp
export PORTAGE_NICENESS=18
export PORTAGE_REPO_DUPLICATE_WARN="0"
#export PORT_LOGDIR=/var/log/portage/

export USE="-bindist -branding -debug -test -pam -systemd -consolekit -policykit -dbus -kdbus -oss -pulseaudio hardened urandom ipv6 sasl ssl libressl -gnutls -nettle threads nptl nls unicode bzip2 lzo lzma xz zlib readline fortran clang gmp openmp ghc smp"
#static-libs
#priority decreases from left to right
export USE_ORDER="pkg:env:conf:defaults:pkginternal:repo:env.d"
#export USE_ORDER="env:pkg:conf:defaults:pkginternal:repo:env.d"

export CONFIG_PROTECT="-*"
export LINGUAS="af ar as ast az be bg bn bo br brx bs ca ca@valencia ca_XV cs csb cy da de dgo dz el en en_GB en_ZA eo es et eu fa fi fo fr fy ga gd gl gu gu_IN ha he hi hr hsb hu ia id is it ja ka kk km kn kn_IN ko kok ks ku lb lo lt lv mai mi mk ml mn mni mr ms mt my nb nds ne nl nn nr nso oc om or pa pa_IN pl pt pt_BR ro ru rw sa_IN sat sd se sh si sk sl sq sr ss st sv sw sw_TZ ta ta_IN te tg th tn tr ts tt ug uk uz ve ven vi wa xh zh_CN zh_HK zh_TW zu"
#FEATURES="userfetch userpriv candy"
#FEATURES="splitdebug"
#INSTALL_MASK="/usr/lib/debug"
#PYTHON_SINGLE_TARGET="python2_7"
#PYTHON_TARGETS="python2_7 python3_5 python3_6"
export SHELL="/bin/bash"
export COLLISION_IGNORE="/usr/share/vim/* /usr/bin/smfsh"

export PORTAGE_CHECKSUM_FILTER="-* sha256"
export PORTAGE_COMPRESS="gzip"
export PORTAGE_COMPRESS_FLAGS="-1"
export BINPKG_COMPRESS="lzop"
export BINPKG_COMPRESS_FLAGS="-1"
