#!/bin/bash

# EVALUATION ORDER
# catalystrc sets ENVIRONMENT as may any other script do
# if no VAR is set in ENVIRONMENT make.conf sets variable
# catalyst-spec is additive to already set USE flags
# ENVIRONMENT supersedes package.use specific flags set

#MAKEOPTS="-j8" -> this overrides parallel/non-parallel settings applied by catalyst/portage
export EMERGE_DEFAULT_OPTS="--verbose y --verbose-conflicts --verbose-slot-rebuilds y --binpkg-respect-use y --deep --complete-graph y --load-average 8.0 --jobs=128 --accept-properties=-interactive"
export PORTAGE_CHECKSUM_FILTER="-* sha256"
export PORTAGE_COMPRESS="gzip"
export PORTAGE_COMPRESS_FLAGS="-1"
export BINPKG_COMPRESS="lzop"
export BINPKG_COMPRESS_FLAGS="-1"

export CHOST=x86_64-pc-linux-gnu
export CFLAGS="-Os -pipe -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"
export CXXFLAGS="-Os -pipe -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fomit-frame-pointer"
export CPU_FLAGS_X86="mmx mmxext sse sse2 sse3"
#
export SWITCH_CTARGET=x86_64-pc-linux-gnu-8.2.0

export PROFILE_IS_HARDENED=1
export ACCEPT_KEYWORDS="~amd64"
export USE="-bindist -branding -debug -test -pam -systemd -consolekit -policykit -dbus -kdbus -oss -pulseaudio hardened urandom ipv6 sasl ssl libressl -gnutls -nettle threads nptl nls unicode bzip2 lzo lzma xz zlib readline fortran clang gmp openmp ghc smp"
#static-libs
#priority decreases from left to right
#export USE_ORDER="env:pkg:conf:defaults:pkginternal:repo:env.d"
export USE_ORDER="pkg:env:conf:defaults:pkginternal:repo:env.d"

export CONFIG_PROTECT="-*"
#export LINGUAS="af ar as ast az be bg bn bo br brx bs ca ca@valencia ca_XV cs csb cy da de dgo dz el en en_GB en_ZA eo es et eu fa fi fo fr fy ga gd gl gu gu_IN ha he hi hr hsb hu ia id is it ja k  a kk km kn kn_IN ko kok ks ku lb lo lt lv mai mi mk ml mn mni mr ms mt my nb nds ne nl nn nr nso oc om or pa pa_IN pl pt pt_BR ro ru rw sa_IN sat sd se sh si sk sl sq sr ss st sv sw sw_TZ t  a ta_IN te tg th tn tr ts tt ug uk uz ve ven vi wa xh zh_CN zh_HK zh_TW zu"
export ACCEPT_LICENSE="-* @FREE"
#FEATURES="userfetch userpriv candy"
#FEATURES="splitdebug"
#INSTALL_MASK="/usr/lib/debug"
#export PYTHON_SINGLE_TARGET="python2_7"
#export PYTHON_TARGETS="python2_7 python3_5 python3_6"
export SHELL="/bin/bash"

export COLLISION_IGNORE="/usr/share/vim/* /usr/bin/smfsh"

export PORTAGE_NICENESS=18
export PORTAGE_REPO_DUPLICATE_WARN="0"
export PORTAGE_TMPDIR=/var/tmp
