#!/bin/bash

# overrides package.env specific noparallel if set here so profile/package.bashrc specific override is required
export MAKEOPTS="-j8 -l8"

export CHOST="x86_64-unknown-linux-uclibc"
export CHOST_amd64="x86_64-unknown-linux-uclibc"
#export CHOST_amd64="x86_64-gentoo-linux-uclibc"
#export CTARGET="x86_64-unknown-linux-uclibc" breaks
#export SWITCH_CTARGET=x86_64-pc-linux-gnu-8.2.0
#export SWITCH_CTARGET=x86_64-unknown-linux-uclibc-8.3.0

export ACCEPT_KEYWORDS="~amd64"
export ACCEPT_LICENSE="-* @FREE"
export PROFILE_IS_HARDENED=1
export PAX_MARKINGS="PT"

#if these are set package.env specific CFLAGS do not override environment with package specific CFLAGS
export CFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -fomit-frame-pointer"
export CXXFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -fomit-frame-pointer"
export COMMON_FLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -fomit-frame-pointer"
export BOOT_CFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -fomit-frame-pointer"
export STAGE1_CFLAGS="-Os -pipe -mmmx -msse -msse2 -msse3 -fomit-frame-pointer"

export EMERGE_DEFAULT_OPTS="--verbose y --verbose-conflicts --verbose-slot-rebuilds y --binpkg-respect-use y --deep --complete-graph y --load-average 8.0 --jobs=64 --accept-properties=-interactive"

#export DISTDIR="/usr/distfiles" conflicts
#export PKGDIR="/var/tmp/packages" conflicts
#export PORTDIR_OVERLAY="/usr/local/portage"
export PORTDIR="/usr/portage"
export PORTAGE_TMPDIR=/var/tmp
export PORTAGE_NICENESS=18
export PORTAGE_REPO_DUPLICATE_WARN="0"
#export PORT_LOGDIR=/var/log/portage/

#export ELIBC=uclibc
export USE="-bindist -branding -debug -test -pam -systemd -consolekit -policykit -dbus -kdbus -oss -pulseaudio -udev acl caps hardened pax-kernel pie pic ssp uclibc urandom ipv6 sasl ssl libressl -gnutls -nettle threads nptl -idn -iconv -nls unicode bzip2 lzo lzma xz zlib readline fortran gmp openmp ghc smp -introspection pch"
# these break stage1 build already
#export BOOTSTRAP_USE=
#static-libs
#priority decreases from left to right
export USE_ORDER="pkg:env:conf:defaults:pkginternal:repo:env.d"

export CONFIG_PROTECT="-*"
export LINGUAS="af ar as ast az be bg bn bo br brx bs ca ca@valencia ca_XV cs csb cy da de dgo dz el en en_GB en_ZA eo es et eu fa fi fo fr fy ga gd gl gu gu_IN ha he hi hr hsb hu ia id is it ja ka kk km kn kn_IN ko kok ks ku lb lo lt lv mai mi mk ml mn mni mr ms mt my nb nds ne nl nn nr nso oc om or pa pa_IN pl pt pt_BR ro ru rw sa_IN sat sd se sh si sk sl sq sr ss st sv sw sw_TZ ta ta_IN te tg th tn tr ts tt ug uk uz ve ven vi wa xh zh_CN zh_HK zh_TW zu"
#FEATURES="userfetch userpriv candy"
#FEATURES="userfetch"
export FEATURES="-usersandbox -sandbox userfetch userpriv sfperms strict"
#FEATURES="splitdebug"
#INSTALL_MASK="/usr/lib/debug"
export SHELL="/bin/bash"
export COLLISION_IGNORE="/usr/share/vim/* /usr/libexec/cups/driver /usr/libexec/cups/driver/* /usr/bin/smfsh /usr/bin/iconv /usr/include/iconv.h"

export PORTAGE_CHECKSUM_FILTER="-* sha256"
export PORTAGE_COMPRESS="gzip"
export PORTAGE_COMPRESS_FLAGS="-1"
export BINPKG_COMPRESS="lzop"
export BINPKG_COMPRESS_FLAGS="-1"
