#!/bin/sh

/etc/rc.local.d/rc.default

hostname localhost

# make /lib/firmware writeable and modprobe radeon
/usr/local/bin/firmware.sh
rmmod radeon; modprobe radeon ; umount /mnt/livecd/lib64/firmware

# wake on lan
ifconfig enp35s0 10.0.0.1/8; ethtool -s enp35s0 wol u

# reset and start firewall
/etc/rc.local.d/rc.fwstop
/etc/rc.local.d/rc.fwstart

fscky -y /dev/disk/by-label/HOME
fscky -y /dev/disk/by-label/DISTFILES
#fscky -y /dev/disk/by-label/TMP
mount /dev/disk/by-label/HOME /home/
mount /dev/disk/by-label/DISTFILES /home/distfiles
#mount /dev/disk/by-label/TMP /home/tmp

sync
echo 3 > /proc/sys/vm/drop_caches

#eject /dev/sr0

/usr/local/bin/locketc.sh
#/usr/local/bin/sleep.sh
