#!/bin/sh

/etc/rc.local.d/rc.default

hostname darkstar

mkdir -p /media/lvm/lvcatalyst /media/lvm/lvdocuments /media/lvm/lvgames /media/lvm/lvimages /media/lvm/lvmovies /media/lvm/lvmusic /media/lvm/lvsource /media/lvm/lvwindows

# make /lib/firmware writeable and modprobe radeon
/usr/local/bin/firmware.sh
rmmod radeon; modprobe radeon; umount /mnt/livecd/lib64/firmware

ifconfig enp0s25 10.0.0.2/8

# load sound modules
modprobe snd-mixer-oss ; modprobe snd-pcm-oss; modprobe snd-seq-oss

# add static arp entry for build server wake on lan
arp -s 10.0.0.1 ec:08:6b:05:bb:56

# reset and start firewall
/etc/rc.local.d/rc.fwstop
/etc/rc.local.d/rc.fwstart

# allow portage to fetch distfiles
iptables -A OUTPUT -m owner --gid-owner 250 -d 192.168.0.0/16,172.16.0.0/16,10.0.0.0/8,127.0.0.1 -j DROP
iptables -A OUTPUT -m owner --gid-owner 250 -j ACCEPT

# proxy rules
iptables -t nat -I OUTPUT 1 -p TCP -m owner --uid-owner proxy01 -j DNAT --to-destination 127.0.0.1:8118
iptables -t nat -I OUTPUT 1 -p TCP -m owner --uid-owner proxy02 -j DNAT --to-destination 127.0.0.1:8228
iptables -t nat -I OUTPUT 1 -p TCP -m owner --uid-owner proxy03 -j DNAT --to-destination 127.0.0.1:8338
# prevent dns leaks
iptables -t nat -I OUTPUT 1 -p UDP --to-destination !127.0.0.1 --dport 53 -j DNAT --to-destination 127.0.0.1

# set time
sg lanout -c "ntpdate 172.16.2.1"

# default users and groups
groupadd -g 44444440 fw01
groupadd -g 44444441 proxy01
groupadd -g 44444442 proxy02
groupadd -g 44444443 proxy03
groupadd -g 44444444 proxy04
groupadd -g 6666666 public
groupadd -g 9999999 documents
groupadd -g 66669999 user
groupadd -g 99996666 office
groupadd -g 77777777 gamer

useradd -M -u 44444440 -G fw01 fw01
useradd -M -u 44444441 -G proxy01 proxy01
useradd -M -u 44444442 -G proxy02 proxy02
useradd -M -u 44444443 -G proxy02 proxy03
useradd -M -u 44444444 -G proxy02 proxy04

useradd -M -u 66669999 -G user,portage,wheel,wanout,lanout,public,documents user
useradd -M -u 99996666 -G office,wanout,lanout,public,documents office
useradd -M -u 77777777 -G audio,video,wanout,public gamer
#input, games

echo 'root:$6$rounds=5000000$Ba/xs5f3VIo9$WzQQnpPal2FGbW3gJUeHQBcaNC3hs9Lf.aiEuyk9j1pRW0u0hH8heA9Ss88QU3IQOzzqI4xoSmN4m3BgJge0e0' | chpasswd -e
echo 'user:$6$rounds=5000000$9bDJfEHwH//FUm$P8sRwdeLLzTJk1eyRVr.op8.uSOz40YnwDtF.9euiM/yCCOmxDREPPN7FdlVJCRuzYEas6DoqthBrzt28wkL9.' | chpasswd -e
echo 'office:$6$rounds=5000000$2Cx9OWSpoHAZec3$CCBDiJtMVzBQeDKW0ruSHHivcUCTsdla1UqVYNNFcyJAMlD5d7Y7ligq3fTeruA7unxIzC0LGmiG5cplk9I0G0' | chpasswd -e
echo 'gamer:$6$rounds=5000000$WPAMyx3hYH/nmSgR$m9oeDutTavXkMLJOTyAWWBkS99mit.ZNjsHScwk8VnBIZ7UPRXT0uE332IEolbsFjXtuvDrq9YdWtONGAWj6i/' | chpasswd -e

sync
eject /dev/sr0
/usr/local/bin/locketc.sh
#/usr/local/bin/sleep.sh
