#!/bin/sh

/etc/rc.local.d/rc.default

hostname darkstar

mkdir -p /media/lvm/lvcatalyst /media/lvm/lvdocuments /media/lvm/lvgames /media/lvm/lvimages /media/lvm/lvmovies /media/lvm/lvmusic /media/lvm/lvsource /media/lvm/lvseeds /media/lvm/lvwindows

# make /lib/firmware writeable and modprobe radeon
/usr/local/bin/firmware.sh
rmmod radeon; modprobe radeon; umount /mnt/livecd/lib64/firmware
modprobe psmouse

# load sound modules
modprobe snd-mixer-oss ; modprobe snd-pcm-oss; modprobe snd-seq-oss

# passwords
echo 'user:$6$rounds=5000000$9bDJfEHwH//FUm$P8sRwdeLLzTJk1eyRVr.op8.uSOz40YnwDtF.9euiM/yCCOmxDREPPN7FdlVJCRuzYEas6DoqthBrzt28wkL9.' | chpasswd -e
echo 'user:$6$rounds=5000000$80Xhu/No$eRqjXrW8ZGVdenePhNZugz7XLPwzzMXKx.caJQN/CRLs5QNMP1bDrZh4.4RdOc5/XcODq/cyP4w4a1V76FFqm0' | chpasswd -e
echo 'office:$6$rounds=5000000$2Cx9OWSpoHAZec3$CCBDiJtMVzBQeDKW0ruSHHivcUCTsdla1UqVYNNFcyJAMlD5d7Y7ligq3fTeruA7unxIzC0LGmiG5cplk9I0G0' | chpasswd -e
echo 'gamer:$6$rounds=5000000$WPAMyx3hYH/nmSgR$m9oeDutTavXkMLJOTyAWWBkS99mit.ZNjsHScwk8VnBIZ7UPRXT0uE332IEolbsFjXtuvDrq9YdWtONGAWj6i/' | chpasswd -e

# add static arp entry for build server wake on lan
arp -s 10.0.0.1 ec:08:6b:05:bb:56

# reset and start firewall
/etc/rc.local.d/rc.fwstop
/etc/rc.local.d/rc.fwstart

# allow portage to fetch distfiles
iptables -A OUTPUT -m owner --gid-owner 250 -d 192.168.0.0/16,172.16.0.0/16,10.0.0.0/8,127.0.0.1 -j DROP
iptables -A OUTPUT -m owner --gid-owner 250 -j ACCEPT
# proxy connect chain
iptables -I OUTPUT 1 -m owner --gid-owner $(id -g squid) -d 127.0.0.1 -j ACCEPT
iptables -I OUTPUT 1 -m owner --gid-owner $(id -g privoxy) -d 127.0.0.1 -j ACCEPT
#iptables -I OUTPUT 1 -m owner --gid-owner $(id -g tor) -d 127.0.0.1 -j ACCEPT
# disallow proxy to lan traffic
iptables -A OUTPUT -m owner --gid-owner $(id -g squid) -d 192.168.0.0/16,172.16.0.0/16,10.0.0.0/8 -j DROP
iptables -A OUTPUT -m owner --gid-owner $(id -g privoxy) -d 192.168.0.0/16,172.16.0.0/16,10.0.0.0/8 -j DROP
iptables -A OUTPUT -m owner --gid-owner $(id -g tor) -d 192.168.0.0/16,172.16.0.0/16,10.0.0.0/8 -j DROP
# allow outgoing tor
iptables -A OUTPUT -m owner --gid-owner $(id -g tor) -j ACCEPT

# prevent dns leaks
iptables -I OUTPUT 1 -p UDP -d 127.0.0.1 --dport 53 -j ACCEPT
iptables -I INPUT 1 -p UDP -d 127.0.0.1 --dport 53 -j ACCEPT
iptables -I OUTPUT 1 -p TCP -d 127.0.0.1 --dport 53 -j ACCEPT
iptables -I INPUT 1 -p TCP -d 127.0.0.1 --dport 53 -j ACCEPT
#iptables -t nat -I PREROUTING 1 -p UDP ! -d 127.0.0.1 --dport 53 -j DNAT --to 127.0.0.1
# ddclient
iptables -A OUTPUT -p UDP -m owner --uid-owner $(id -u ddclient) -d 127.0.0.1 --dport 53 -j ACCEPT
iptables -A OUTPUT -p UDP -m owner --uid-owner $(id -u ddclient) --dport 53 -j ACCEPT
iptables -A OUTPUT -p TCP -m owner --uid-owner $(id -u ddclient) -d 84.45.76.100 --dport 443 -j ACCEPT
iptables -A OUTPUT -p TCP -m owner --uid-owner $(id -u ddclient) -d 84.45.76.100 --dport 80 -j ACCEPT
iptables -A OUTPUT -p UDP -m owner --gid-owner $(id -g ddclient) -d 127.0.0.1 --dport 53 -j ACCEPT
iptables -A OUTPUT -p TCP -m owner --gid-owner $(id -g ddclient) -d 84.45.76.100 --dport 443 -j ACCEPT
iptables -A OUTPUT -p TCP -m owner --gid-owner $(id -g ddclient) -d 84.45.76.100 --dport 80 -j ACCEPT

#echo "MOUNT LVM"
/usr/local/bin/mountlvm.sh

#echo "LAUNCH FW01"
/usr/local/bin/fw01.sh

#echo "WAItINT 120s for FW01"
sleep 120

# enable network and sync time
ifconfig enp0s25 10.0.0.2/8
/usr/local/bin/dhclient enp0s26u1u2u1u5
sleep 5
/usr/local/bin/timesync.sh

# start proxies
/usr/local/bin/tor.sh
/usr/local/bin/privoxy.sh
/usr/local/bin/squid.sh

cp -pf /usr/local/etc/ddclient/ddclient.conf /etc/ddclient/ddclient.conf
/etc/init.d/ddclient restart

echo "nameserver 127.0.0.1" > /etc/resolv.conf

echo 'Section "Device"'				>> /etc/X11/xorg.conf
echo 'Identifier "radeon0"'			>> /etc/X11/xorg.conf
echo 'Driver "radeon"'				>> /etc/X11/xorg.conf
echo 'Option "SwapbuffersWait" "false"'		>> /etc/X11/xorg.conf
echo 'Option "TearFree" "off"'			>> /etc/X11/xorg.conf
echo 'Option "EXAVSync" "off"'			>> /etc/X11/xorg.conf
echo 'Option "AccelMethod" "glamor"'		>> /etc/X11/xorg.conf
echo 'Option "ColorTiling" "on"'		>> /etc/X11/xorg.conf
echo 'Option "ColorTiling2D" "on"'		>> /etc/X11/xorg.conf
echo 'Option "EnablePageFlip" "off"'		>> /etc/X11/xorg.conf
echo 'Option "ShadowPrimary" "off"'		>> /etc/X11/xorg.conf
echo 'Option "DRI" "3"'				>> /etc/X11/xorg.conf
echo 'EndSection'				>> /etc/X11/xorg.conf
echo >>  /etc/X11/xorg.conf

# auto high, when set to auto with xorg started powersafe kicks in
echo auto > /sys/class/drm/card0/device/power_dpm_force_performance_level
# battery balanced performance, with xorg running powersafe kicks in regardless of state set, framebuffer sets mode to high
echo performance > /sys/class/drm/card0/device/power_dpm_state

sync
echo 3 > /proc/sys/vm/drop_caches

#eject /dev/sr0

/usr/local/bin/locketc.sh
#/usr/local/bin/sleep.sh
