subarch: amd64
version_stamp: latest
target: livecd-stage2
rel_type: hardened
profile: hardened/linux/amd64/no-multilib
snapshot: latest
source_subpath: hardened/livecd-stage1-amd64-latest.tar.bz2
portage_confdir: /home/autobuild/etc/portage/
portage_overlay: /usr/local/portage

livecd/volid: Hardened Desktop Live System
livecd/type: generic-livecd
livecd/iso: amd64-latest.iso
livecd/fstype: none
livecd/gk_mainargs: --mdadm --makeopts=-j8 --config=/etc/portage/genkernel.conf --no-oldconfig
livecd/cdtar: /home/autobuild/etc/portage/catalyst/livecd/cdtar/isolinux-3.86-cdtar.tar.bz2
livecd/bootargs: net.ifnames=0 dokeymap nodhcp memory_corruption_check=1
livecd/rcdel: keymaps|boot netmount|default
livecd/rcadd: cronie|default rsyslog|default
# sshd|default sshguard|default
livecd/root_overlay: /home/autobuild/rootfs/default
livecd/overlay: /home/autobuild/rootfs/desktop
#livecd/xdm:

boot/kernel: linux
boot/kernel/linux/sources: ck-sources
boot/kernel/linux/config: /home/autobuild/etc/portage/kconfig

boot/kernel/linux/use:
	-awt -bindist -branding -debug -consolekit -dbus -kdbus -policykit -pam -systemd -oss -pulseaudio -udisks -upower -upnp -upnp-av -avahi -gvfs -gtk3 -qt4 -qt5 -gnome-keyring -libnotify -gnome -kde -java -ruby -python -test hardened urandom ipv6 crypt sasl ssl libressl curl_ssl_libressl -gnutls -nettle socks5 system-mitkrb5 usb threads nptl nls unicode bzip2 lzo lzma xz zlib xml static-libs
	-udev
	-wayland
	-gconf
	smp
	clang
	X
	doc
	gtk
	gtk2
	xcb
	xkb
	alsa
	alsa_pcm_plugins_adpcm
	alsa_pcm_plugins_alaw
	alsa_pcm_plugins_asym
	alsa_pcm_plugins_copy
	alsa_pcm_plugins_dmix
	alsa_pcm_plugins_dshare
	alsa_pcm_plugins_dsnoop
	alsa_pcm_plugins_empty
	alsa_pcm_plugins_extplug
	alsa_pcm_plugins_file
	alsa_pcm_plugins_hooks
	alsa_pcm_plugins_iec958
	alsa_pcm_plugins_ioplug
	alsa_pcm_plugins_ladspa
	alsa_pcm_plugins_lfloat
	alsa_pcm_plugins_linear
	alsa_pcm_plugins_meter
	alsa_pcm_plugins_mmap_emul
	alsa_pcm_plugins_mulaw
	alsa_pcm_plugins_multi
	alsa_pcm_plugins_null
	alsa_pcm_plugins_plug
	alsa_pcm_plugins_rate
	alsa_pcm_plugins_route
	alsa_pcm_plugins_share
	alsa_pcm_plugins_shm
	alsa_pcm_plugins_softvol
	fluidsynth
	jack
	speex
	icu
	gd
	djvu
	bmp
	gif
	jpeg
	jpeg2k
	mng
	png
	apng
	svg
	tiff
	fluidsynth
	midi
	gstreamer
	a52
	aac
	flac
	gsm
	lame
	ladspa
	ogg
	openal
	vorbis
	wav
	mad
	mp3
	mp4
	mpeg
	speex
	theora
	ffmpeg
	xvid
	x264
	h323
	v4l
	cdda
	cddb
	css
	dvb
	dvd
	sdl
	scanner
	joystick
	sound
	video
	#egl
	#gles
	#gles2
	#gles3
	opengl
	gallium
	glamor
	uxa
	sna
	dri
	dri2
	dri3
	vaapi
	vdpau
	xa
	xv
	xvmc
	video_cards_amdgpu
	video_cards_apm
	video_cards_ast
	video_cards_chips
	video_cards_cirrus
	video_cards_dummy
	video_cards_epson
	video_cards_fbdev
	video_cards_glint
	video_cards_i128
	video_cards_i740
	video_cards_intel
	video_cards_i915
	video_cards_i965
	video_cards_mach64
	video_cards_mga
	video_cards_neomagic
	video_cards_nouveau
	video_cards_nv
	video_cards_r128
	video_cards_radeon
	video_cards_radeonsi
	video_cards_rendition
	video_cards_s3
	video_cards_s3virge
	video_cards_savage
	video_cards_siliconmotion
	video_cards_sisusb
	video_cards_tdfx
	video_cards_tga
	video_cards_trident
	video_cards_tseng
	video_cards_vesa
	video_cards_via
	video_cards_voodoo
	video_cards_nvidia
	-video_cards_fglrx
	-video_cards_geode
	-video_cards_freedreno
	-video_cards_omap
	-video_cards_omapfb
	-video_cards_qxl
	-video_cards_sunbw2
	-video_cards_suncg14
	-video_cards_suncg3
	-video_cards_suncg6
	-video_cards_sunffb
	-video_cards_sunleo
	-video_cards_suntcx
	-video_cards_tegra
	-video_cards_virtualbox
	-video_cards_vmware
	input_devices_acecad
	input_devices_aiptek
	input_devices_elographics
	input_devices_fpit
	input_devices_hyperpen
	input_devices_joystick
	input_devices_keyboard
	input_devices_libinput
	input_devices_mouse
	input_devices_mutouch
	input_devices_penmount
	input_devices_tslib
	input_devices_vmmouse
	input_devices_void
	input_devices_synaptics
	input_devices_wacom
	-input_devices_evdev
	mmx
	sse
	sse2
	ntfsprogs
	-ntfsdecrypt
	libusb
	cairo
	imlib
	sqlite
	truetype
	fontconfig
	latex
	jadetex
	xetex
	fortran

boot/kernel/linux/packages:
	app-admin/sudo
	#app-arch/alien
	#app-arch/rpm
	app-backup/amanda
	#app-backup/bacula
	#app-benchmarks/httperf
	#app-cdr/graveman
	#app-crypt/johntheripper
	#app-doc/cppman
	app-doc/abs-guide
	app-doc/autobook
	app-doc/devmanual
	app-doc/elisp-manual
	app-doc/linkers-and-loaders
	app-doc/linux-device-drivers
	app-doc/linuxfromscratch
	app-doc/single-unix-specification
	app-doc/selfhtml
	app-doc/tldp-howto
	app-doc/phrack-all
	#app-dicts/stardict*
	#app-editors/emacs
	#app-emacs/
	#app-emulation/fuse
	#app-emulation/fuse-utils
	#app-emulation/ganeti
	#app-forensics/autopsy
	#app-forensics/cmospwd
	app-forensics/examiner
	app-forensics/memdump
	#app-forensics/openscap
	app-forensics/pasco
	#app-forensics/libewf
	#app-forensics/rdd
	#app-forensics/rkhunter
	#app-forensics/rdd
	app-forensics/scalpel
	app-forensics/volatility
	app-forensics/yasat
	# patch required to drop dbus dependency
	#app-leechcraft/leechcraft-meta
	#app-misc/jail
	#app-misc/pax-utils
	#app-mobilephone/smssend
	app-office/dia2code
	#app-office/openerp
	#app-office/planner
	#app-office/gnumeric
	#app-office/skrooge
	#app-office/scribus
	#app-officeext/ooo2gd
	#app-office/grisbi
	app-office/lyx
	app-officeext/barcode
	app-officeext/dmaths
	app-officeext/sun-templates
	app-officeext/texmaths
	#app-pda/gtkpod
	#app-pda/ipodslave
	#app-xemacs/
	#dev-ada
	#dev-cpp
	dev-cpp/clucene
	dev-cpp/lucene++
	#dev-db/
	#dev-db/mysql
	#dev-db/sqlitestudio
	#dev-dotnet/
	#dev-embedded/
	#dev-erlang/
	#dev-games/
	#dev-go/
	#dev-haskell/
	#dev-java/
	dev-lang/php
	dev-lang/swig
	#dev-libs/
	#dev-lisp/
	#dev-lua/
	#dev-ml/
	#dev-perl/
	#dev/php/
	#dev-python/
	#dev-qt/
	#dev-ros/
	#dev-ruby/
	#dev-scheme/
	#dev-tcltk/
	#dev-tex/
	#dev-texlive/
	#dev-util/
	#dev-vcs/
	#games-action/
	#games-arcade/
	#games-board/
	#games-emulation/
	#games-engines/
	games-fps/darkplaces
	games-fps/freespace-scp
	games-fps/xonotic
	games-fps/yamagi-quake2
	games-simulation/flightgear
	games-simulation/lincity-ng
	games-strategy/widelands
	#games-kids/
	#games-misc/
	#games-mud/
	#games-puzzle/
	#games-roguelike/
	#games-rpg/
	#games-server/
	#games-simulation/
	#games-sports/
	games-strategy/0ad
	games-strategy/asc
	games-strategy/crimson
	games-strategy/warzone2100
	games-strategy/wesnoth
	games-strategy/widelands
	games-util/jstest-gtk
	#gnome-base/
	#gnome-extra/
	#gnustep-apps/
	#gnustep-base/
	#gnustep-libs/
	#java-virtuals/
	#kde-apps/
	#kde-base/
	#kde-frameworks/
	#kde-misc/
	#kde-plasma/
	#lxde-base/
	#lxqt-base/
	#mail-client/
	#mail-filter/
	#mail-mta/
	#mate-base/
	#mate-extra/
	#media-fonts/
	media-gfx/blender
	#media-libs/
	#media-plugins/
	#media-radio/
	media-sound/audacity
	#media-sound/grip
	media-sound/hydrogen
	media-sound/mumble
	#media-sound/rhythmbox
	#media-tv/
	#media-tv/w_scan
	#net-analyzer/amap
	net-analyzer/authforce
	net-analyzer/bing
	net-analyzer/bmon
	#net-analyzer/bro
	#net-analyzer/bsnmp
	net-analyzer/bwm-ng
	net-analyzer/calamaris
	net-analyzer/cnet
	#net-analyzer/dsniff
	net-analyzer/ethloop
	net-analyzer/ftester
	net-analyzer/fwlogwatch
	#net-analyzer/httping
	#net-analyzer/hydra
	net-analyzer/ifstat
	#net-analyzer/ipgen
	net-analyzer/iplog
	net-analyzer/ipsumdump
	net-analyzer/isic
	#net-analyzer/metasploit
	#net-analyzer/nagircbot
	#net-analyzer/nagvis
	#net-analyzer/nrpe
	#net-analyzer/namebench
	#net-analyzer/ndsad
	#blocks nessus-core
	#net-analyzer/nessus
	#net-analyzer/nessus-bin
	#net-analyzer/nessus-client
	#net-analyzer/nessus-core
	#net-analyzer/nessus-libraries
	#net-analyzer/nessus-plugins
	#net-analyzer/libnasl
	net-analyzer/nettop
	net-analyzer/netwatch
	#net-analyzer/nikto
	#net-analyzer/openvas
	#net-analyzer/ospd
	#net-analyzer/portbunny
	net-analyzer/portmon
	net-analyzer/sarg
	#net-analyzer/ssldump
	#net-analyzer/sslscan
	#net-analyzer/sslsniff
	net-analyzer/synscan
	#net-analyzer/tcpreplay
	#net-analyzer/testssl
	#net-analyzer/thc-ipv6
	#net-dialup/wvdial
	net-dns/pdnsd
	#net-firewall/fwbuilder
	#net-firewall/ipset
	#net-firewall/ipt_netflow
	#https://bugs.gentoo.org/show_bug.cgi?id=583608
	#net-firewall/nufw
	#net-firewall/xtables-addon
	#net-fs/
	#net-im/silc-server
	#net-im/skype
	#net-misc/connman
	#net-misc/socat
	#net-nds/lat
	#conflict with nfs-utils
	#net-nds/portmap
	#net-nds/ypbind
	#broken
	#net-nds/yp-tools
	#net-news/
	#net-nntp/
	#net-p2p/
	#net-print/
	#broken
	#net-proxy/ziproxy
	#net-voip/blink
	#net-voip/ekiga
	#net-wireless/airpwn
	#net-wireless/hostap-utils
	#net-wireless/hostapd
	#net-wireless/kismet
	#net-wireless/kismet-ubertooth
	#net-wireless/lorcon
	net-wireless/mfoc
	net-wireless/rfkill
	#perl-core/
	#ros-meta/
	#sci-astronomy/
	#sci-biology/
	sci-calculators/pcalc
	sci-calculators/units
	sci-calculators/wcalc
	#sci-chemistry/
	#sci-electronics/
	#sci-geosciences/
	#sci-libs/
	#sci-mathematics/
	#sci-misc/
	#sci-physics/
	#sci-visualization/
	#sci-calculators/calcoo
	#sci-calculators/calculator
	#sci-calculators/tiemu
	sci-calculators/tilp2
	#sec-policy/
	#sys-apps/
	#sys-auth/skey
	#sys-block/
	#sys-boot/
	#sys-cluster/
	#sys-devel/
	#sys-fabric/
	#sys-firmware/
	#sys-freebsd/
	#sys-fs/
	#sys-kernel/
	#sys-libs/
	#sys-power/
	#sys-process/
	sys-process/memwatch
	sys-process/nmon
	#www-apache/
	#www-apps/
	#www-client/
	#www-misc/
	#www-plugins/
	#www-servers/
	www-servers/apache
	#x11-apps/
	#x11-base/
	#x11-drivers/
	#x11-libs/
	#x11-misc/
	#x11-plugins/
	#x11-proto/
	#x11-terms/
	#x11-themes/
	#x11-wm/
	#xfce-base/
	#xfce-extra/

#livecd/unmerge:
#	sys-libs/pam
#	sys-auth/pambase

livecd/rm:
	#/lib/firmware/*
	/boot/System*
	/boot/initr*
	/boot/kernel*
	/etc/make.conf*
	/etc/make.globals
	/etc/make.profile
	/var/tmp/gentoo.config
	/var/tmp/genkernel/initramfs*
	/usr/src/linux

#livecd/empty:

livecd/fsscript: /home/autobuild/finalize_target.sh
